name: Pull Request - Application

on:
  pull_request:
    branches: 
      - main

jobs:
  modules:
    uses: codbex/codbex-infra/.github/workflows/module-pull-request.yaml@main
    with:
      packages-build: codbex-hestia
    secrets: inherit
  application:
    needs: modules
    uses: codbex/codbex-infra/.github/workflows/application-pull-request.yaml@main
    with:
      application-name: codbex-hestia
    secrets: inherit
