name: Release - Application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  modules:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-hestia
      packages-build: codbex-hestia
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-hestia - ${{ inputs.release-version }}
  
        Warehouse Management - Dashboard
  
        ## Installation
  
        ```
        npm install @codbex/codbex-hestia@${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - [/services/web/codbex-hestia/gen/](http://localhost:80/services/web/codbex-hestia/gen/) - Admin Panel
    secrets: inherit